version: '3'

services:
  serverrabbit:
    build: serverrabbit/
    image: mabouchacra/serverrabbit:1.0
    ports:
      - "5672:5672"
      - "15672:15672"
  stormproducer:
    build: stormproducer/
    image: mabouchacra/stormproducer:1.0
    depends_on:
      - serverrabbit
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  jedifactory:
    build: jedifactory/
    image: mabouchacra/jedifactory:1.0
