version: '2'
services:
  serverrabbit:
    image: rabbitmq:3.6.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: serverrabbit
  stormproducer:
    build: stormproducer
    container_name: stormproducer
  jedifactory:
    build: jedifactory
    container_name: jedifactory
