#!/bin/bash

docker service create --name zenika-nightclazz-rep --detach=false --publish 5000:5000 registry:2

cd stormproducer
docker tag nc-swarm/stormproducer localhost:5000/zenika-nightclazz-rep:stormproducer
cd ../serverrabbit
docker tag nc-swarm/serverrabbit localhost:5000/zenika-nightclazz-rep:serverrabbit
cd ../jedifactory
docker tag nc-swarm/jedifactory localhost:5000/zenika-nightclazz-rep:jedifactory
cd ..

docker-compose push

docker stack deploy --compose-file docker-stack.yml stacked
#docker stack services stacked -> pour voir si tout va bien

# docker logs etc... (pb : impossible de se connecter à l'interface de rabbitmq ou de lancer un curl mais # un les logs de jedifactory me reponde bien "Message received : Attack!!! Stormtrooper!! N°:57")


# jouer avec les replicas.....
# A compléter


# On enlève tout
#docker stack rm stacked
#docker rm zenika-nightclazz-rep
#docker swarm leave
